<?php

/**
 * Implementation of hook_menu
 */
function relation_bulk_add_menu(){
  $items = array();
  $items['admin/structure/relation/bulkadd'] = array(
    'title' => 'Bulk Add Relationships',
    'page callback' => 'drupal_get_form',
    'page arguments' => array('relation_bulk_add_form'),
    'access callback' => TRUE,
    'type' => MENU_CALLBACK
  );
  return $items;
}


function relation_bulk_add_form($form, &$form_state, $relationstring=''){
  $relation = relation_type_load($relationstring);
  
  // Todo. Remove these restrictions and TEST everything.
  if(!$relation ||
          $relation->directional != 1 ||
          $relation->min_arity != 2 ||
          $relation->max_arity != 2 ||
          $relation->r_unique != 1) {
    drupal_set_message('Unfortunatley, this relation type uses settings that are not yet compatible with Bulk Add. At this stage we only accept directional relations with max arity of 2. We also only accept a single entity type as source or target.');
    return array();
  }
  
  $entity = relation_create($relationstring, array());
  field_attach_form('relation', $entity, $form, $form_state);
  
  // Get all possible sources (limiting by bundle as appropriate)
  $source = explode(':', $relation->source_bundles[0]);
  
  //handlers for "relation" a a source vs eck...
  $type_string = ($source[0] == 'relation')?'relation_type':'type';
  $id_string = ($source[0] == 'relation')?'rid':'id';
  
  
  $query = new EntityFieldQuery();
  $query->entityCondition('entity_type', $source[0], '=');
  if($source[1] != '*'){ $query->propertyCondition($type_string, $source[1], '='); }
  $result = $query->execute();
  $ids = array();
  foreach($result[$source[0]] as $record) {
    $ids[] = $record->$id_string;
  }
  $sources = entity_load($source[0], $ids);
  foreach($sources as $key => $value){
    //List of possible source entities to choose from
    //debug($value);
    if($source[0] == 'relation'){
      $title = array();
      //todo: Construct a natural-language title for relation
      foreach($value->endpoints['und'] as $endpoint){
        $endpoint_obj = entity_load($endpoint['entity_type'], array($endpoint['entity_id']));
        //debug($endpoint_obj[$endpoint['entity_id']]->title);
        $title[] = $endpoint_obj[$endpoint['entity_id']]->title;
      }
      //debug($title);
      $title = implode(' // ', $title);
    } else { $title = $value->title; }
    $source_select[$key] = $title; 
  }
  
  // Get all possible targets (limiting by bundle as appropriate)
  $target = explode(':', $relation->target_bundles[0]);
  $query = new EntityFieldQuery();
  $query->entityCondition('entity_type', $target[0], '=');
  if($target[1] != '*'){ $query->propertyCondition('type', $target[1], '='); }
  $result = $query->execute();
  $ids = array();
  foreach($result[$target[0]] as $record) {
    $ids[] = $record->id;
  }
  $targets = entity_load($target[0], $ids);
  foreach($targets as $key => $value){
    //List of possible target entities to choose from
    $target_select[$key] = $value->title;
  }
  
  // Construct a form
  
  $form['relation_type'] = array(
      '#type' => 'value',
      '#value' => $relationstring,
  );
  $form['source'] = array(
      '#type' => 'select',
      '#title' => t('Source'),
      '#options' => $source_select,
  );
  $form['source_type'] = array(
      '#type' => 'value',
      '#value' => $source[0],
  );
  
  $form['target'] = array(
      '#type' => 'checkboxes',
      '#title' => t('Targets'),
      '#options' => $target_select,
  );
  $form['target_type'] = array(
      '#type' => 'value',
      '#value' => $target[0],
  );
  
  $form['submit'] = array(
      '#type' => 'submit',
      '#value' => t('Save'),
      '#weight' => 1000,
  );
  
  return $form;
}

function relation_bulk_add_form_submit($form, &$form_state){
  $i=0;
  foreach($form_state['values']['target'] as $targid){
    if($targid > 0){
      $relation = relation_create($form_state['values']['relation_type'], array(
          array('entity_type' => $form_state['values']['source_type'], 'entity_id' => $form_state['values']['source']),
          array('entity_type' => $form_state['values']['target_type'], 'entity_id' => $targid),
          ));
      entity_form_submit_build_entity('relation', $relation, $form, $form_state);
      $rid = relation_save($relation);
      if($rid){ $i++; }
    }
  }
  drupal_set_message($i.' Relationships Created.');
}